# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_pipeline\pw_pipeline\assets\houdini\python\VEX\pw_Houdini_VEX_Editor\pw_VEX_Editor\widgets\options_dialog.ui'
#
# Created: Thu Mar 17 10:41:34 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(425, 601)
        self.verticalLayout_7 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 421, 597))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.font_preview_lb = QtGui.QLabel(self.groupBox)
        self.font_preview_lb.setMinimumSize(QtCore.QSize(100, 50))
        self.font_preview_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.font_preview_lb.setObjectName("font_preview_lb")
        self.verticalLayout.addWidget(self.font_preview_lb)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.font_size_sld = QtGui.QSlider(self.groupBox)
        self.font_size_sld.setMinimum(8)
        self.font_size_sld.setMaximum(60)
        self.font_size_sld.setOrientation(QtCore.Qt.Horizontal)
        self.font_size_sld.setObjectName("font_size_sld")
        self.horizontalLayout.addWidget(self.font_size_sld)
        self.font_size_spb = QtGui.QSpinBox(self.groupBox)
        self.font_size_spb.setMinimum(8)
        self.font_size_spb.setMaximum(60)
        self.font_size_spb.setProperty("value", 12)
        self.font_size_spb.setObjectName("font_size_spb")
        self.horizontalLayout.addWidget(self.font_size_spb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.font_name_cbb = QtGui.QFontComboBox(self.groupBox)
        self.font_name_cbb.setObjectName("font_name_cbb")
        self.verticalLayout.addWidget(self.font_name_cbb)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.auto_update_parameters_cbx = QtGui.QCheckBox(self.groupBox_2)
        self.auto_update_parameters_cbx.setChecked(True)
        self.auto_update_parameters_cbx.setObjectName("auto_update_parameters_cbx")
        self.verticalLayout_3.addWidget(self.auto_update_parameters_cbx)
        self.create_parms_on_top = QtGui.QCheckBox(self.groupBox_2)
        self.create_parms_on_top.setObjectName("create_parms_on_top")
        self.verticalLayout_3.addWidget(self.create_parms_on_top)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.auto_save_tabs_cbx = QtGui.QCheckBox(self.groupBox_3)
        self.auto_save_tabs_cbx.setChecked(True)
        self.auto_save_tabs_cbx.setObjectName("auto_save_tabs_cbx")
        self.verticalLayout_5.addWidget(self.auto_save_tabs_cbx)
        self.create_backup_cbx = QtGui.QCheckBox(self.groupBox_3)
        self.create_backup_cbx.setChecked(True)
        self.create_backup_cbx.setObjectName("create_backup_cbx")
        self.verticalLayout_5.addWidget(self.create_backup_cbx)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.aurocompleter_cbx = QtGui.QCheckBox(self.groupBox_4)
        self.aurocompleter_cbx.setChecked(True)
        self.aurocompleter_cbx.setObjectName("aurocompleter_cbx")
        self.verticalLayout_2.addWidget(self.aurocompleter_cbx)
        self.show_whitespaces_cbx = QtGui.QCheckBox(self.groupBox_4)
        self.show_whitespaces_cbx.setObjectName("show_whitespaces_cbx")
        self.verticalLayout_2.addWidget(self.show_whitespaces_cbx)
        self.show_toolbar_cbx = QtGui.QCheckBox(self.groupBox_4)
        self.show_toolbar_cbx.setChecked(True)
        self.show_toolbar_cbx.setObjectName("show_toolbar_cbx")
        self.verticalLayout_2.addWidget(self.show_toolbar_cbx)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.use_online_manual_cbx = QtGui.QCheckBox(self.groupBox_5)
        self.use_online_manual_cbx.setObjectName("use_online_manual_cbx")
        self.verticalLayout_6.addWidget(self.use_online_manual_cbx)
        self.use_external_browser_cbx = QtGui.QCheckBox(self.groupBox_5)
        self.use_external_browser_cbx.setObjectName("use_external_browser_cbx")
        self.verticalLayout_6.addWidget(self.use_external_browser_cbx)
        self.help_window_cbx = QtGui.QCheckBox(self.groupBox_5)
        self.help_window_cbx.setObjectName("help_window_cbx")
        self.verticalLayout_6.addWidget(self.help_window_cbx)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.save_btn = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout_4.addWidget(self.save_btn)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.font_size_sld, QtCore.SIGNAL("valueChanged(int)"), self.font_size_spb.setValue)
        QtCore.QObject.connect(self.font_size_spb, QtCore.SIGNAL("valueChanged(int)"), self.font_size_sld.setValue)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "VEX Editor Options", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Font", None, QtGui.QApplication.UnicodeUTF8))
        self.font_preview_lb.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Font size preview</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.font_preview_lb.setText(QtGui.QApplication.translate("Dialog", "Font Example ( 123 + 456 );", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Default Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.font_size_sld.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Font size</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.font_size_spb.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Font size</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Font Family", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_update_parameters_cbx.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Update spare parameters on save action</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_update_parameters_cbx.setText(QtGui.QApplication.translate("Dialog", "Auto Update Spare Patameters On Save", None, QtGui.QApplication.UnicodeUTF8))
        self.create_parms_on_top.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Create new spare parameters on top of node UI</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.create_parms_on_top.setText(QtGui.QApplication.translate("Dialog", "Create Spare Parameters on Top", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_save_tabs_cbx.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Save opened tabs in current HIP file</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_save_tabs_cbx.setText(QtGui.QApplication.translate("Dialog", "Auto Save Tabs In HIP", None, QtGui.QApplication.UnicodeUTF8))
        self.create_backup_cbx.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Save opened tabs in current HIP file</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.create_backup_cbx.setText(QtGui.QApplication.translate("Dialog", "Create backup", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.aurocompleter_cbx.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Show whitespaces in editor</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.aurocompleter_cbx.setText(QtGui.QApplication.translate("Dialog", "Autocompleter", None, QtGui.QApplication.UnicodeUTF8))
        self.show_whitespaces_cbx.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Show whitespaces in editor</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.show_whitespaces_cbx.setText(QtGui.QApplication.translate("Dialog", "Show Whitespaces", None, QtGui.QApplication.UnicodeUTF8))
        self.show_toolbar_cbx.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Show whitespaces in editor</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.show_toolbar_cbx.setText(QtGui.QApplication.translate("Dialog", "Show Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.use_online_manual_cbx.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Open quick help from sidefx.com</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.use_online_manual_cbx.setText(QtGui.QApplication.translate("Dialog", "Use Online Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.use_external_browser_cbx.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Use default Houdini web browser or standart system web browser</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.use_external_browser_cbx.setText(QtGui.QApplication.translate("Dialog", "Use External Browser For Quick Help", None, QtGui.QApplication.UnicodeUTF8))
        self.help_window_cbx.setToolTip(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Use default Houdini web browser or standart system web browser</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.help_window_cbx.setText(QtGui.QApplication.translate("Dialog", "Show Help WIndow", None, QtGui.QApplication.UnicodeUTF8))
        self.save_btn.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))

