# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_pipeline\pw_pipeline\assets\houdini\python\VEX\pw_Houdini_VEX_Editor\pw_VEX_Editor\widgets\options_dialog.ui'
#
# Created: Mon Apr 18 09:24:41 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

try:
    from PySide.QtCore import *
    from PySide.QtGui import *
except:
    from PySide2.QtCore import *
    from PySide2.QtGui import *
    from PySide2.QtWidgets import *

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(425, 575)
        self.verticalLayout_7 = QVBoxLayout(Dialog)
        self.verticalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 421, 571))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.font_preview_lb = QLabel(self.groupBox)
        self.font_preview_lb.setMinimumSize(QSize(100, 50))
        self.font_preview_lb.setAlignment(Qt.AlignCenter)
        self.font_preview_lb.setObjectName("font_preview_lb")
        self.verticalLayout.addWidget(self.font_preview_lb)
        self.line = QFrame(self.groupBox)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.font_size_sld = QSlider(self.groupBox)
        self.font_size_sld.setMinimum(8)
        self.font_size_sld.setMaximum(60)
        self.font_size_sld.setOrientation(Qt.Horizontal)
        self.font_size_sld.setObjectName("font_size_sld")
        self.horizontalLayout.addWidget(self.font_size_sld)
        self.font_size_spb = QSpinBox(self.groupBox)
        self.font_size_spb.setMinimum(8)
        self.font_size_spb.setMaximum(60)
        self.font_size_spb.setProperty("value", 12)
        self.font_size_spb.setObjectName("font_size_spb")
        self.horizontalLayout.addWidget(self.font_size_spb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.font_name_cbb = QFontComboBox(self.groupBox)
        self.font_name_cbb.setObjectName("font_name_cbb")
        self.verticalLayout.addWidget(self.font_name_cbb)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.auto_update_parameters_cbx = QCheckBox(self.groupBox_2)
        self.auto_update_parameters_cbx.setChecked(True)
        self.auto_update_parameters_cbx.setObjectName("auto_update_parameters_cbx")
        self.verticalLayout_3.addWidget(self.auto_update_parameters_cbx)
        self.create_parms_on_top = QCheckBox(self.groupBox_2)
        self.create_parms_on_top.setObjectName("create_parms_on_top")
        self.verticalLayout_3.addWidget(self.create_parms_on_top)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.auto_save_tabs_cbx = QCheckBox(self.groupBox_3)
        self.auto_save_tabs_cbx.setChecked(True)
        self.auto_save_tabs_cbx.setObjectName("auto_save_tabs_cbx")
        self.verticalLayout_5.addWidget(self.auto_save_tabs_cbx)
        self.create_backup_cbx = QCheckBox(self.groupBox_3)
        self.create_backup_cbx.setChecked(True)
        self.create_backup_cbx.setObjectName("create_backup_cbx")
        self.verticalLayout_5.addWidget(self.create_backup_cbx)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.aurocompleter_cbx = QCheckBox(self.groupBox_4)
        self.aurocompleter_cbx.setChecked(True)
        self.aurocompleter_cbx.setObjectName("aurocompleter_cbx")
        self.verticalLayout_2.addWidget(self.aurocompleter_cbx)
        self.show_whitespaces_cbx = QCheckBox(self.groupBox_4)
        self.show_whitespaces_cbx.setObjectName("show_whitespaces_cbx")
        self.verticalLayout_2.addWidget(self.show_whitespaces_cbx)
        self.show_toolbar_cbx = QCheckBox(self.groupBox_4)
        self.show_toolbar_cbx.setChecked(True)
        self.show_toolbar_cbx.setObjectName("show_toolbar_cbx")
        self.verticalLayout_2.addWidget(self.show_toolbar_cbx)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.use_online_manual_cbx = QCheckBox(self.groupBox_5)
        self.use_online_manual_cbx.setObjectName("use_online_manual_cbx")
        self.verticalLayout_6.addWidget(self.use_online_manual_cbx)
        self.use_external_browser_cbx = QCheckBox(self.groupBox_5)
        self.use_external_browser_cbx.setObjectName("use_external_browser_cbx")
        self.verticalLayout_6.addWidget(self.use_external_browser_cbx)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.save_btn = QPushButton(self.scrollAreaWidgetContents)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout_4.addWidget(self.save_btn)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)

        self.retranslateUi(Dialog)
        QObject.connect(self.font_size_sld, SIGNAL("valueChanged(int)"), self.font_size_spb.setValue)
        QObject.connect(self.font_size_spb, SIGNAL("valueChanged(int)"), self.font_size_sld.setValue)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QApplication.translate("Dialog", "VEX Editor Options", None))
        self.groupBox.setTitle(QApplication.translate("Dialog", "Font", None))
        self.font_preview_lb.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Font size preview</p></body></html>", None))
        self.font_preview_lb.setText(QApplication.translate("Dialog", "Font Example ( 123 + 456 );", None))
        self.label.setText(QApplication.translate("Dialog", "Default Font Size", None))
        self.font_size_sld.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Font size</p></body></html>", None))
        self.font_size_spb.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Font size</p></body></html>", None))
        self.label_2.setText(QApplication.translate("Dialog", "Font Family", None))
        self.groupBox_2.setTitle(QApplication.translate("Dialog", "Parameters", None))
        self.auto_update_parameters_cbx.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Update spare parameters on save action</p></body></html>", None))
        self.auto_update_parameters_cbx.setText(QApplication.translate("Dialog", "Auto Update Spare Patameters On Save", None))
        self.create_parms_on_top.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Create new spare parameters on top of node UI</p></body></html>", None))
        self.create_parms_on_top.setText(QApplication.translate("Dialog", "Create Spare Parameters on Top", None))
        self.groupBox_3.setTitle(QApplication.translate("Dialog", "Tabs", None))
        self.auto_save_tabs_cbx.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Save opened tabs in current HIP file</p></body></html>", None))
        self.auto_save_tabs_cbx.setText(QApplication.translate("Dialog", "Auto Save Tabs In HIP", None))
        self.create_backup_cbx.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Save opened tabs in current HIP file</p></body></html>", None))
        self.create_backup_cbx.setText(QApplication.translate("Dialog", "Create backup", None))
        self.groupBox_4.setTitle(QApplication.translate("Dialog", "Editor", None))
        self.aurocompleter_cbx.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Show whitespaces in editor</p></body></html>", None))
        self.aurocompleter_cbx.setText(QApplication.translate("Dialog", "Autocompleter", None))
        self.show_whitespaces_cbx.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Show whitespaces in editor</p></body></html>", None))
        self.show_whitespaces_cbx.setText(QApplication.translate("Dialog", "Show Whitespaces", None))
        self.show_toolbar_cbx.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Show whitespaces in editor</p></body></html>", None))
        self.show_toolbar_cbx.setText(QApplication.translate("Dialog", "Show Toolbar", None))
        self.groupBox_5.setTitle(QApplication.translate("Dialog", "Help", None))
        self.use_online_manual_cbx.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Open quick help from sidefx.com</p></body></html>", None))
        self.use_online_manual_cbx.setText(QApplication.translate("Dialog", "Use Online Manual", None))
        self.use_external_browser_cbx.setToolTip(QApplication.translate("Dialog", "<html><head/><body><p>Use default Houdini web browser or standart system web browser</p></body></html>", None))
        self.use_external_browser_cbx.setText(QApplication.translate("Dialog", "Use External Browser For Quick Help", None))
        self.save_btn.setText(QApplication.translate("Dialog", "Save", None))

