# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_pipeline\pw_pipeline\assets\houdini\python\VEX\pw_VEX_Editor\widgets\template_editor.ui'
#
# Created: Sun Oct 25 01:18:32 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_templateEditor(object):
    def setupUi(self, templateEditor):
        templateEditor.setObjectName("templateEditor")
        templateEditor.resize(631, 602)
        self.verticalLayout = QtGui.QVBoxLayout(templateEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(templateEditor)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.splitter = QtGui.QSplitter(templateEditor)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.templates_ly = QtGui.QVBoxLayout(self.layoutWidget)
        self.templates_ly.setContentsMargins(0, 0, 0, 0)
        self.templates_ly.setObjectName("templates_ly")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtGui.QPushButton(self.layoutWidget)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.remove_btn = QtGui.QPushButton(self.layoutWidget)
        self.remove_btn.setObjectName("remove_btn")
        self.horizontalLayout.addWidget(self.remove_btn)
        self.templates_ly.addLayout(self.horizontalLayout)
        self.templates_lw = QtGui.QListWidget(self.layoutWidget)
        self.templates_lw.setObjectName("templates_lw")
        self.templates_ly.addWidget(self.templates_lw)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.keyword_ly = QtGui.QHBoxLayout()
        self.keyword_ly.setObjectName("keyword_ly")
        self.keyword_le = QtGui.QLineEdit(self.layoutWidget1)
        self.keyword_le.setObjectName("keyword_le")
        self.keyword_ly.addWidget(self.keyword_le)
        self.horizontalLayout_2.addLayout(self.keyword_ly)
        self.cursorpos_btn = QtGui.QPushButton(self.layoutWidget1)
        self.cursorpos_btn.setObjectName("cursorpos_btn")
        self.horizontalLayout_2.addWidget(self.cursorpos_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.text_widget_ly = QtGui.QVBoxLayout()
        self.text_widget_ly.setObjectName("text_widget_ly")
        self.verticalLayout_2.addLayout(self.text_widget_ly)
        self.verticalLayout.addWidget(self.splitter)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.save_btn = QtGui.QPushButton(templateEditor)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_4.addWidget(self.save_btn)
        self.cancel_btn = QtGui.QPushButton(templateEditor)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_4.addWidget(self.cancel_btn)
        self.open_btn = QtGui.QPushButton(templateEditor)
        self.open_btn.setObjectName("open_btn")
        self.horizontalLayout_4.addWidget(self.open_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(templateEditor)
        QtCore.QMetaObject.connectSlotsByName(templateEditor)
        templateEditor.setTabOrder(self.add_btn, self.remove_btn)
        templateEditor.setTabOrder(self.remove_btn, self.templates_lw)
        templateEditor.setTabOrder(self.templates_lw, self.cursorpos_btn)
        templateEditor.setTabOrder(self.cursorpos_btn, self.save_btn)
        templateEditor.setTabOrder(self.save_btn, self.cancel_btn)

    def retranslateUi(self, templateEditor):
        templateEditor.setWindowTitle(QtGui.QApplication.translate("templateEditor", "Live Template Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("templateEditor", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("templateEditor", "<html><head/><body><p>Press <span style=\" font-weight:600;\">TAB</span> key after <span style=\" font-weight:600;\">keyword </span>to insert Templates into VEX Editor</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.add_btn.setText(QtGui.QApplication.translate("templateEditor", "Add New", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_btn.setText(QtGui.QApplication.translate("templateEditor", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("templateEditor", "Keyword", None, QtGui.QApplication.UnicodeUTF8))
        self.cursorpos_btn.setToolTip(QtGui.QApplication.translate("templateEditor", "<html><head/><body><p>Set position to move cursor after apllaying template</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cursorpos_btn.setText(QtGui.QApplication.translate("templateEditor", "$cursor$", None, QtGui.QApplication.UnicodeUTF8))
        self.save_btn.setText(QtGui.QApplication.translate("templateEditor", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_btn.setText(QtGui.QApplication.translate("templateEditor", "Cance", None, QtGui.QApplication.UnicodeUTF8))
        self.open_btn.setText(QtGui.QApplication.translate("templateEditor", "Open Folder", None, QtGui.QApplication.UnicodeUTF8))

