# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_pipeline\pw_pipeline\assets\houdini\python\VEX\pw_VEX_Editor\widgets\theme_editor.ui'
#
# Created: Tue Nov 03 22:46:53 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(946, 618)
        self.verticalLayout_6 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtGui.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.theme_gb = QtGui.QGroupBox(self.layoutWidget)
        self.theme_gb.setObjectName("theme_gb")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.theme_gb)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.themes_cbb_ly = QtGui.QHBoxLayout()
        self.themes_cbb_ly.setObjectName("themes_cbb_ly")
        self.verticalLayout_2.addLayout(self.themes_cbb_ly)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.remove_btn = QtGui.QPushButton(self.theme_gb)
        self.remove_btn.setObjectName("remove_btn")
        self.gridLayout_2.addWidget(self.remove_btn, 0, 2, 1, 1)
        self.save_btn = QtGui.QPushButton(self.theme_gb)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 0, 0, 1, 1)
        self.save_as_btn = QtGui.QPushButton(self.theme_gb)
        self.save_as_btn.setObjectName("save_as_btn")
        self.gridLayout_2.addWidget(self.save_as_btn, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addWidget(self.theme_gb)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.houdini_theme_cbb = QtGui.QComboBox(self.groupBox_2)
        self.houdini_theme_cbb.setObjectName("houdini_theme_cbb")
        self.verticalLayout_7.addWidget(self.houdini_theme_cbb)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 713, 432))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.picker_gb = QtGui.QGroupBox(self.layoutWidget1)
        self.picker_gb.setObjectName("picker_gb")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.picker_gb)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.picker_ly = QtGui.QHBoxLayout()
        self.picker_ly.setObjectName("picker_ly")
        self.horizontalLayout_2.addLayout(self.picker_ly)
        self.color_info_ly = QtGui.QVBoxLayout()
        self.color_info_ly.setContentsMargins(15, -1, -1, -1)
        self.color_info_ly.setObjectName("color_info_ly")
        self.color_label_ly = QtGui.QVBoxLayout()
        self.color_label_ly.setObjectName("color_label_ly")
        self.color_info_ly.addLayout(self.color_label_ly)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.color_info_ly.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.color_info_ly)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_5.addWidget(self.picker_gb)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.preview_ly = QtGui.QVBoxLayout(self.groupBox_3)
        self.preview_ly.setObjectName("preview_ly")
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_6.addWidget(self.splitter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Theme Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.theme_gb.setTitle(QtGui.QApplication.translate("Dialog", "Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_btn.setText(QtGui.QApplication.translate("Dialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.save_btn.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.save_as_btn.setText(QtGui.QApplication.translate("Dialog", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Houdini Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Colors", None, QtGui.QApplication.UnicodeUTF8))
        self.picker_gb.setTitle(QtGui.QApplication.translate("Dialog", "Picker", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Preview", None, QtGui.QApplication.UnicodeUTF8))

